# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running prepare scripts
RUN pnpm install --frozen-lockfile --ignore-scripts

# Copy the rest of the project
COPY . ./

# Create entrypoint script to generate .env from environment variables
RUN echo '#!/bin/sh' > entrypoint.sh \
    && echo 'if [ ! -f /app/.env ]; then' >> entrypoint.sh \
    && echo '  echo "ADAMIK_API_KEY=$ADAMIK_API_KEY" >> /app/.env' >> entrypoint.sh \
    && echo '  echo "ADAMIK_API_BASE_URL=$ADAMIK_API_BASE_URL" >> /app/.env' >> entrypoint.sh \
    && echo '  echo "STARKNET_PRIVATE_KEY=$STARKNET_PRIVATE_KEY" >> /app/.env' >> entrypoint.sh \
    && echo 'fi' >> entrypoint.sh \
    && echo 'exec node build/index.js' >> entrypoint.sh \
    && chmod +x entrypoint.sh

# Build the project
RUN pnpm run build

# Default command
CMD ["sh", "entrypoint.sh"]
